apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-script
spec:
  selector:
    matchLabels:
      app: python-script
  template:
    metadata:
      labels:
        app: python-script
    spec:
      containers:
      - name: python-script
        image: localhost:5000/test
        ports:
        - containerPort: 5000
